# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: check-symlinks
    -   id: destroyed-symlinks
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
    -   id: flake8
        # check for Python syntax errors and undefined names
        args: ['--select=E9,F63,F7,F82']
        # # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
